URL_SERVICE = "https://cnt-f2a6b824-60fa-4c88-8ae0-c07906c51462.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users"
CREATE_KITS_PATH = "/api/v1/kits"
